name: 'Check changes of JSON values'
description: 'Check changes of JSON values'
inputs:
  githubToken:
    description: 'Github Token'
    required: true
  compareKeys:
    description: 'Object keys to compare (JSON encoded)'
    required: true
outputs:
  valuesMatch: # id of output
    description: 'Whether the values of the compared jsons match'
runs:
  using: 'node12'
  main: 'index.js'
