name: 'Check changes of JSON values'
description: 'Check changes of JSON values'
main: 'dist/index.js'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  myToken:
    description: 'Github Token'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
