name: 'Compare JSON values at last two tags'
description: 'This action compares a json file at the last two tags and determines if any of the given values have changed.'
inputs:
  githubToken:
    description: 'Github Token'
    required: true
  compareKeys:
    description: 'Object keys to compare (JSON encoded)'
    required: true
  filePath:
    description: 'Path to the JSON file to check'
    required: true
outputs:
  valuesMatch: # id of output
    description: 'Whether the values of the compared jsons match'
runs:
  using: 'node12'
  main: '.github/actions/compare-tagged-json/dist/index.js'
