on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/actions/compare-tagged-json # Uses an action in the root directory
        id: compare
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compareKeys: '["value"]'
          filePath: 'app.json'
      # Use the output from the `compare` step
      - name: Do the values match?
        run: echo "Values match - ${{ steps.compare.outputs.valuesMatch }}"
